name: Build native code

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    name: Build
    strategy:
      matrix:
        node: ['18', '20']
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Setup MSFS SDK
        uses: koesie10/setup-msfs-sdk@v1
        with:
          url: ${{ secrets.MSFS_SDK_URL }}
      - name: Install Yarn
        run: yarn install
        env:
          CHILD_CONCURRENCY: 1
